### ISSUE TITLE
 /usr/local/bin/node: No such file or directory

### ISSUE THREAD

**Issue by IdealBoy709** [MuYunyun/commonSearch#1]
出现原因：
我的macbook中是使用nvm安装node的，导致这里node无法找到，

解决方案：
是否能通过shell命令获取相关的node的路径，然后动态修改的node代码中的路径

**Comment by MuYunyun** [comment]
@modarend 你在终端输入 node -v 能否打印出相应版本号？ 用 nvm 安装 node 并没有问题的

**Comment by IdealBoy709** [comment]
能够使用node -v，但是本地node的路径和workflow中写的路径是一致的
![image](https://user-images.githubusercontent.com/25577631/44451779-44065080-a627-11e8-9b53-fd0ae56ff923.png)
我现在的做法就是手动修改workflow中路径，如下图
![image](https://user-images.githubusercontent.com/25577631/44452159-5e8cf980-a628-11e8-9f91-0c942449e5b9.png)

我这边也尝试修改bash中执行的脚本
```
node_address=`which node`
$node_address common_search.js 1 "{query}"
```
 但是debug发现bash无法找到node路径。但是我本地的bash这行代码是没问题的，您能看看是什么原因吗？

**Comment by IdealBoy709** [comment]
而且在workflow中即使执行`which nvm`，也是找不到的nvm的。如果能够实现bash获取本地的node路径，然后执行`common_search.js` 我想就能很好的解决这个问题

**Comment by modarend** [comment]
我这用的就是zsh啊

**Comment by IdealBoy709** [comment]
现在node并不在/usr/local/bin/目录下，我查看了本地的目录也是没有的，只存在于.nvm目录下

**Comment by DraculaPrince** [comment]
这是个很严重的问题，如果无法用nvm重的node地址，这个插件的可用性就降低了，因为node路径写死了，需要版本控制node的人怎么办？

**Comment by MuYunyun** [comment]
@DraculaPrince bash 这块我不太熟悉:smile:, 欢迎 pr

**Comment by yangcore** [comment]
可以使用 run-node包，动态获取node地址  ./node_modules/.bin/run-node common_search.js

**Comment by MuYunyun** [comment]
> 可以使用 run-node包，动态获取node地址 ./node_modules/.bin/run-node common_search.js

感觉可行

**Comment by MuYunyun** [comment]
@yangcore @IdealBoy709 已更新, 可以重新下载下。

**Comment by yangcore** [comment]
> @yangcore @ IdealBoy709已更新，可以重新下载下。

测试可以了

**Comment by MuYunyun** [comment]
👍
