### ISSUE TITLE
为什么我输入code 然后输入项目名称 啥也没反应 

### ISSUE THREAD

**Issue by fariellany** [MuYunyun/commonSearch#22]
需要配置什么环境吗 node 我已经有了

**Comment by MuYunyun** [comment]
@fariellany 

1. 双击 code
![image](https://user-images.githubusercontent.com/19354791/130342583-7644038a-e950-42ac-a12a-24ea727a85e3.png)

2. 下划线处更改为你的本地目标路径文件

此外要确保在配置过 `code .` (即在终端执行该命令能启动 vscode)
