### ISSUE TITLE
求添加京东搜索

### ISSUE THREAD

**Issue by shinnchouu** [MuYunyun/commonSearch#28]
有可能添加京东搜索吗, 就像淘宝一样的

**Comment by MuYunyun** [comment]
> 有可能添加京东搜索吗, 就像淘宝一样的

已添加，https://github.com/MuYunyun/flow#%E4%BA%AC%E4%B8%9C%E6%99%BA%E8%83%BD%E6%90%9C%E7%B4%A2%E5%8C%B9%E9%85%8D

**Comment by shinnchouu** [comment]
> > 有可能添加京东搜索吗, 就像淘宝一样的
> 
> 已添加，https://github.com/MuYunyun/flow#%E4%BA%AC%E4%B8%9C%E6%99%BA%E8%83%BD%E6%90%9C%E7%B4%A2%E5%8C%B9%E9%85%8D

nb！
